[package]
name = "bin"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "get"
path = "get.rs"

[[bin]]
name = "parse_cities"
path = "parse_cities.rs"
required-features = ["csv"]

[[bin]]
name = "get_rand"
path = "get_rand.rs"
required-features = ["rand"]

[[bin]]
name = "write"
path = "write.rs"
required-features = ["rocksdb"]

[features]
full = ["rand", "csv", "rocksdb"]

[dependencies]
weather = { path = "../weather" }
ron = "0.6.4"
tokio = { version = "1", features = ["full"] }
rand = { version = "0.8.3", optional = true }
csv = { version = "1.1.6", optional = true }
rocksdb = { version = "0.16.0", optional = true }
bincode = "1.3.3"
