* org
:PROPERTIES:
:ID:       8adf8bc0-3a2f-47ae-860b-1e71e93fc339
:END:
The repo found at [[src:org][hg.rwest.io/org]] contains words I've written in
plaintext. It is packaged and shipped to my other services that
generate content.

The main components are =meta=, which contains information about my
projects and =notes= which contains a collection of notes from
different topics floating around the web.

** Commentary
Emacs is my IDE and text-editor of choice, so Org-mode is a natural
fit for all types of writing I do. The problem with Org is that it is
difficult to parse /outside of Emacs/. in =elisp=, the [[https://orgmode.org/worg/dev/org-element-api.html][org-element api]]
fully supports the specification, but it is a monster task to
re-implement in another language.

While I slowly work out a parser, I have been using the built-in
exporters with some scripts to generate static content.

** Usage
All docs can be viewed online at [[https://rwest.io/meta][rwest.io/meta]] and downloaded at
[[https://pkg.rwest.io/org][pkg.rwest.io/org]] which includes tar.zst archives for the following
formats:
- HTML
- MD
- PDF
- TXT
