* shed
:PROPERTIES:
:ID: 205131fc-ff48-4e0b-a3e8-ab52d5b6ca19
:CATEGORY: bin
:END:
=shed= is a set of tools and services I'm building for dev project
management. It provides version control, package distribution, project
templates, scripts, and everything else I need to get stuff done.

It comes with a single binary for both client and server ops. Global
configuration is controlled by =UserConfig= and per-project
configuration can be enabled with =ProjectConfig=. The specification
of these types cover all options that can be customized.

** Status
*TODO*
- this doesn't work quite yet
- some features are available, but disjointed

** Features
- Mercurial VCS
   - Pullbundles and Clonebundles
   - Subrepos
   - HTTP and SSH authentication
   - HTTP server
   - Git import/export
- Dependency management for any open-source repository
- Build tools (=cargo=, =clang=, =Makefile=, =scripts=)
- Template integration with =babel= for files and projects
- async compression and archiving
- Fully configurable via RON or JSON files

** Overview
The name =shed= was originally derived from [[https://github.com/facebookexperimental/rust-shed][rust-shed]], a set of common
Rust crates used internally by Facebook. I first wrote about it in
April, in a post where I introduced some projects and goals
for 2021. Since then the scope has expanded and mutated
significantly[fn:1] as I've found the time to do further testing. Our
=shed= is not specific to the Rust programming language, doesn't
provide a public API, and resembles =rust-shed= in name
only[fn:2].

** Usage
Once the binary is installed it can be executed to bootstrap a
=UserConfig= via CLI prompts or download one remotely. A user
configuration file needs to be available and accessible by the current
user. The default path is ~$HOME/.config/shed.ron~ but can be
overridden by ~$SHED_CONFIG~ environment variable.

*** TODO Configuration

*** TODO Version Control

*** TODO Dependency Management

*** TODO Build tools

*** TODO Distribution

*** TODO Templates

** Footnotes
[fn:1]  =shed= is not based on a single concrete type like a
=package=, and fully encompasses the =lab= project management tool
initially introduced.

[fn:2] =rlib= on the other hand, is very similar to =rust-shed= and
other crates Facebook has open-sourced such as [[https://github.com/facebookincubator/gazebo][gazebo]].

