* Emacs
:PROPERTIES:
:ID:       0f13e326-614c-4df9-8344-e257eb165d8c
:END:
** [[src:config/emacs][my emacs config]]
** Building from Source
First, clone the repo:
#+begin_src shell :results silent
git clone https://git.savannah.gnu.org/git/emacs.git /tmp/emacs
#+end_src

Once the source is in hand, I stronly recommend making a separate
build directory and calling the configure script from there.

#+begin_src shell
mkdir /tmp/emacs-build && cd /tmp/emacs-build
../emacs/configure --with-mailutils --with-imagemagick --with-x-toolkit=athena --without-pop --without-sound --with-json --enable-link-time-optimization --with-native-compilation
NATIVE_FULL_AOT=1 make -j8
# test the build with './src/emacs' (location of output binary)
# install emacs binaries on current system
make install
#+end_src

The =configure= script takes a bunch of different flags that
customize the build, and generate a build-specific Makefile.

The next line compiles the source. Install with =make install= and
you're done! A custom Emacs binary with all the fixings has just
been installed for your current user. :)

Here are some of the other configuration flags worth investigating:

- --without-all
- --with-x-toolkit=no
- --without-x
- --without-dbus --without-gconf --without-gsettings

** Org Mode                                                            :org:
:PROPERTIES:
:ID: 0b4c27b4-3c1a-41c3-afcd-048f2cf15030
:END:
https://orgmode.org/

Org-mode is a flexible text-based note-taking system built for [[file:emacs.org][Emacs]].

It's one of the best packages available in the Emacs ecosystem and
really pushes the boundaries of what simple 'text-files' are capable
of. It can be intimidating at first look, but if you keep diving down
the rabbit-hole it feels like a whole new world is opened up to
you.

My usage of org-mode revolves around the following principles:
- /Documentation is highly valuable/ - There is no religion without a
  prophet.
- /Workflows are not stable/ - There is no one-size-fits-all solution
  to workflow management. Org-mode configurations will change over
  time, and that's ok. It also allows us to keep with the latest
  trends in the community 87).
- /Inspect and Adapt/ - I have weekly review seshes to take a glimpse
  at my current workflow from afar, and jot down a list of things that
  work, and things that don't. Good habit to get into for serious
  usage.

*** Tutorials
**** Getting Started with Org Mode - Harry Schwartz
[[yt:SzA2YODtgK4][Getting Started With Org Mode]]

** straight.el
:PROPERTIES:
:ID: 9711fba3-2682-400e-9c72-54bdc07a15d5
:END:
- https://github.com/raxod502/straight.el

=straight.el= is a modern replacement for [[file:package_el.org][package.el]] with a built-in
wrapper for [[file:use-package.org][use-package]] declarations, and a modular structure which
makes it easy to define custom package /recipes/.

- The way this package initializes is by being bootstrapped in the
  early stages of our Emacs startup with the following script:
  #+name: sraight-bootstrap
  #+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
  #+end_src

** [[https://opensource.com/article/20/3/blog-emacs][How to blog with Emacs Org mode | Opensource.com]] :org:publish:
CREATED: [2020-07-30 Thu 22:26]
uses =ox-publish= to create a sitemap in =publish.el=, and executes
that code with a Makefile.
** [[https://www.gnu.org/software/emacs/manual/html_mono/widget.html][The Emacs Widget Library]]                                             :ui:
	 :PROPERTIES:
	 :CREATED:  [2020-07-24 Fri]
	 :END:
** [[https://protesilaos.com/dotemacs/#h:847477fe-ef86-4e12-a2da-6c431528da99][GNU Emacs integrated computing environment | Protesilaos Stavrou]]
	 :PROPERTIES:
	 :CREATED:  [2020-07-23 Thu]
	 :END:
** [[https://orgmode.org/worg/dev/org-element-api.html][Org Element API]]                                                 :org:api:
	 :PROPERTIES:
	 :CREATED:  [2020-07-23 Thu]
	 :END:
** [[http://ergoemacs.org/emacs/elisp_parse_org_mode.html][Elisp: Parse Org Mode]]                                           :org:api:
	 :PROPERTIES:
	 :CREATED:  [2020-07-23 Thu]
	 :END:
** [[https://orgmode.org/worg/org-tutorials/weaving-a-budget.html][Weaving a budget with Org & ledger]]
	 :PROPERTIES:
	 :CREATED:  [2020-07-23 Thu]
	 :END:
** [[https://orgmode.org/worg/org-tutorials/tracking-habits.html][Tracking Habits with Org-mode]]                                       :org:
	 :PROPERTIES:
	 :CREATED:  [2020-07-23 Thu]
	 :END:
** [[https://emacs.stackexchange.com/questions/9674/customize-startup-screen-text][start up - Customize startup screen text - Emacs Stack Exchange]]
	 :PROPERTIES:
	 :CREATED:  [2020-07-23 Thu]
	 :END:
** [[https://www.johndcook.com/blog/2016/06/15/ascii-art-diagrams-in-emacs-org-mode/][Emacs org-mode ASCII diagrams]]                                       :org:
	 :PROPERTIES:
	 :CREATED:  [2020-07-22 Wed]
	 :END:
	 use ditaa n00bz
** [[https://www.johndcook.com/blog/2012/02/09/python-org-mode/][Running Python and R inside Emacs]]
	 :PROPERTIES:
	 :CREATED:  [2020-07-22 Wed]
	 :END:

** [[https://orgmode.org/manual/Creating-Footnotes.html][Creating Footnotes (The Org Manual)]]                                 :org:
	 :PROPERTIES:
	 :CREATED:  [2020-07-11 Sat]
	 :END:

** [[https://www.emacswiki.org/emacs/Icicles][Icicles - EmacsWiki]]
:PROPERTIES:
:ID:       88d7f5f9-f5c6-4283-9ac1-88881ea4cfae
:CREATED: [2021-01-39 Sat 11:01]
:END:
Emacs lib for enhancing minibuffer completion
   

** [[https://www.emacswiki.org/emacs/BookmarkPlus][bookmark+ docs]]
:PROPERTIES:
:ID:       1d87a1fb-4e0d-4f78-949a-2247c702abac
:CREATED: [2021-02-06 Sat 03:02]
:END:
** [[http://cachestocaches.com/2016/9/my-workflow-org-agenda/][My Workflow with Org-Agenda]]                                         :org:
:PROPERTIES:
:ID:       fd929d43-cb4c-4021-90ab-2b2a94729f5c
:CREATED: [2021-01-26 Tue 18:49]
:END:
A classic emacs beginner read
** [[https://orgmode.org/manual/HTML-Export.html#HTML-Export][Emacs Org HTML Export]]                                               :org:
:PROPERTIES:
:ID:       d7675cbb-9f74-4b96-a2ff-ac85de916deb
:CREATED: [2021-01-20 Wed 22:47]
:END:
