#+TITLE: Software Defined Radio
#+ID: de73cf8a-d39f-4bdb-8ec9-009288e77d19
- https://en.wikipedia.org/wiki/Software-defined_radio

* [[https://www.wikiwand.com/en/Cognitive_radio?fbclid=IwAR2ix1x1HHC9rimSUr_NkdRQERtKKm4_IBvH25Vb05Oh6svQ3mKegV0bKz0][Cognitive Radio]]
* [[https://www.wikiwand.com/en/RF_front_end][RF Front End]]
#+BEGIN_QUOTE
In a radio receiver circuit, the RF front end is a generic term for all the circuitry between a receiver's antenna input up to and including the mixer stage.[1] It consists of all the components in the receiver that process the signal at the original incoming radio frequency (RF), before it is converted to a lower intermediate frequency (IF). In microwave and satellite receivers it is often called the low-noise block (LNB) or low-noise downconverter (LND) and is often located at the antenna, so that the signal from the antenna can be transferred to the rest of the receiver at the more easily handled intermediate frequency.

For most superheterodyne architectures, the RF front end consists of:[2]

A band-pass filter (BPF) to reduce image response. This removes any signals at the image frequency, which would otherwise interfere with the desired signal. It also prevents strong out-of-band signals from saturating the input stages.
An RF amplifier, often called the low-noise amplifier (LNA). Its primary responsibility is to increase the sensitivity of the receiver by amplifying weak signals without contaminating them with noise, so that they can stay above the noise level in succeeding stages. It must have a very low noise figure (NF). The RF amplifier may not be needed and is often omitted (or switched off) for frequencies below 30 MHz, where the signal-to-noise ratio is defined by atmospheric and man-made noise.
A local oscillator (LO) which generates a radio frequency signal at an offset from the incoming signal, which is mixed with the incoming signal.
The mixer, which mixes the incoming signal with the signal from the local oscillator to convert the signal to the intermediate frequency (IF).#+END_QUOTE
#+END_QUOTE

+ imagine fx processing on radio signals. SDR plguins. encryption, ids, etc


** [[https://www.wikiwand.com/en/Band-pass_filter][band-pass filter]]
** [[https://www.wikiwand.com/en/Amplifier][RF amplifier]]
** [[https://www.wikiwand.com/en/Local_oscillator][local oscillator]]
** [[https://www.wikiwand.com/en/Frequency_mixer][mixer]]
*** [[https://www.wikiwand.com/en/Heterodyne][Heterodyne]]
creates new frequencies by combining or mixing two frequencies.

* Antennai
