#+title: Tokio
- https://tokio.rs/
#+begin_quote
Tokio is an asynchronous runtime for the Rust programming language. It
provides the building blocks needed for writing network
applications. It gives the flexibility to target a wide range of
systems, from large servers with dozens of cores to small embedded
devices.
#+end_quote

* working with UDP
:LOGBOOK:
- noted [2021-08-25 Wed 18:46] \\
  this is for tokio v0.2.0
:END:
UDP connections are handled similarly to TCP in tokio.
  - =tokio::net::UdpSocket= provides core functionality for
    communicating over UDP, in contrast to =TcpListener= and
    =TcpStream=
  - =tokio::net::udp= provides UDP utility types
  - =tokio_util::codec= provides codec utilities to go from a stream
    of bytes to a /Framed/ stream of bytes (AKA a transport)
  - connecting to Socket example:
    [[https://github.com/tokio-rs/tokio/blob/master/examples/connect.rs][tokio/connect.rs at master · tokio-rs/tokio · GitHub]]
    we just care about the =udp= module which reads and writes from
    stdin to a UDP Frame.

