#+TITLE: Using Data
#+ID: 0x0004
#+FILETAGS: :music:weather:
#+DATE: [2021-06-04]
#+INCLUDE: setup.org
#+STARTUP: overview

#+BEGIN_abstract
0x0003 :: Using Data Features Creatively, data-backed programs
#+END_abstract

* Overview

  In [[./02.org][previous posts]], we got some Data from the internet, this post
  will show how to use that Data by writing a couple of programs. Our
  intention is *not* to theorize over some complex system, and instead
  create straight-forward, simple ideas that are easy to inspect and
  understand.

  We start small with a simple color-palette generator in [[*Program A][Program A]]
  that prints an ordered list of [[https://en.wikipedia.org/wiki/Web_colors][color codes]] derived from the current
  weather forecast. The values can be used in CSS stylesheets or piped
  into another program that can read the hex triplets.

  [[*Program B][Program B]] is a software synthesizer that generates Drones based on
  weather forecasts. The audio output is dependent on features of the
  input. Synth parameter values/sequences are inferred implicitly as
  well as from time-series data.

* Program A
** Context
** Code
* Program B
** Context
*** Algorithmic Composition
*** Drones
** Code
   #+begin_src python
   #+end_src

* Program C
